### ISSUE TITLE
Define colors

### ISSUE THREAD

**Issue by enrique-cabrini** [lcabrini/pygame-pong#9]
To be able to add colors to the game to make it more lively, we need to define the colors

**Comment by lcabrini** [comment]
OK. The original pong wasn't very colorful, to tell the truth. But, defining colors is a good idea. We can always make pong in 2017 more colorful. :)

**Comment by enrique-cabrini** [comment]
Okay, I'll work on it

**Comment by lcabrini** [comment]
Good.

**Comment by lcabrini** [comment]
I have merged. Can we close?

**Comment by enrique-cabrini** [comment]
+1
